// Static export names allow Node's ESM loader to expose Electron named imports.
const api = globalThis[Symbol.for('weber.electron.api')];
if (!api) throw new Error('Electron API was imported before Weber initialization');
exports.app = api.app;
exports.BaseWindow = api.BaseWindow;
exports.BrowserWindow = api.BrowserWindow;
exports.webContents = api.webContents;
exports.View = api.View;
exports.WebContentsView = api.WebContentsView;
exports.ipcMain = api.ipcMain;
exports.session = api.session;
exports.webFrameMain = api.webFrameMain;
exports.dialog = api.dialog;
exports.Menu = api.Menu;
exports.MenuItem = api.MenuItem;
exports.globalShortcut = api.globalShortcut;
exports.protocol = api.protocol;
exports.clipboard = api.clipboard;
exports.ClipboardItem = api.ClipboardItem;
exports.MessageChannelMain = api.MessageChannelMain;
